name: ci
on:
  push:
    branches:
      - master

jobs:
  deploy-plumbing:
    runs-on: ubuntu-latest

    steps:
      - name: git pull
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/frese.by/frese
            git pull
      - name: install packages
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/frese.by/frese
            npm install
      - name: build
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/frese.by/frese
            nvm use v16.20.0
            npm run build && npm run generate
            pm2 restart frese